config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  
  devise_scope :admin do
    get "dashboard", :to => "dashboard#index"
    get "dashboard/login", :to => "admins/sessions#new"
    post "dashboard/login", :to => "admins/sessions#create"
    get "dashboard/logout", :to => "admins/sessions#destroy"
  end
  
  namespace :dashboard do
    resources :categories, except: [:new]
  end
    
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }
  
  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post "cart/create", :to => "shopping_carts#create"
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      get "mypage/address/edit", :to => "users#edit_address"
      put "mypage", :to => "users#update"
      get "mypage/edit_password", :to => "users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get "mypage/favorite", :to => "users#favorite"
    end
  end
  
  resources :products do
    member do
      get :favorite
    end
    resources :reviews, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    
    extend DisplayList
    
    
    scope :major_categories, -> { pluck(:major_category_name).uniq }
    
    scope :request_category, -> (category) { find(category.to_i) }
    
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController
    before_action :authenticate_admin!, except: :index
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    layout "dashboard/dashboard"
    
    def index
        @categories = Category.display_list(params[:page])
        @category = Category.new
    end
    
    def show
    end
    
    def create
        category = Category.new(category_params)
        category.save
        redirect_to dashboard_categories_path
    end
    
    def show
    end
    
    def update
        @category.update(category_params)
        @category.save
        redirect_to dashboard_categories_path
    end
    
    def destroy
        @category.destroy
        redirect_to dashboard_categories_path
    end
    
    private
    
    def set_category
        @category = Category.find(params[:id])
    end
    
    def category_params
        params.require(:category).permit(:name, :description, :major_category_name)
    end
        
        
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  layout 'dashboard/dashboard'
  
  def index
  end
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/categories/edit.html.erb
<div class="w-75">
    <h1>カテゴリ情報更新</h1>
    
    <%= form_with model: @category, url: dashboard_category_path(@category), local: true do |f| %>
      <div class="form-group">
          <%= f.label :name, "カテゴリ名" %>
          <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
          <%= f.label :description, "カテゴリの説明" %>
          <%= f.text_field :description, class: "form-control" %>
      </div>
      
      <div class="form-group">
          <%= f.label :major_category_name, "カテゴリ" %>
          <%= f.text_field :major_category_name, class: "form-control" %>
      </div>
      
          <%= f.submit "更新", class: "btn btn-danger" %>
    <% end %>
    <div class="mt-4"><%= link_to "カテゴリ一覧に戻る", dashboard_categories_path %></div>
</div>

app/views/dashboard/categories/index.html.erb
<div class="w-75">
    
    <%= form_with model: @category, url: dashboard_categories_path, local: true do |f| %>
      <div class="form-group">
          <%= f.label :name, "カテゴリ名" %>
          <%= f.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
          <%= f.label :description, "カテゴリの説明" %>
          <%= f.text_field :description, class: "form-control" %>
      </div>
       
      <div class="form-group">
          <%= f.label :major_category_name, "カテゴリ" %>
          <%= f.text_field :major_category_name, class: "form-control" %>
      </div>
      
      <div class="form-group">
          <%= f.submit "+新規作成", class: "btn samazon-submit-button" %>
      </div>
    <% end %>
    
    <table class="table mt-5">
        <thead>
            <tr>
                <th scope="col" class="w-25">ID</th>
                <th scope="col">カテゴリ</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <%= @categories.each do |category| %>
              <tr>
                  <td scope="row"><%= category.id %></td>
                  <td><%= category.name %></td>
                  <td><%= link_to "編集", edit_dashboard_category_path(category), class: "dashboard-edit-link" %></td>
                  <td><%= link_to "削除", dashboard_category_path(category), method: :delete, class: "dashboard-delete-link" %></td>
              </tr>
            <% end %>
        </tbody>
    </table>
    <%= paginate @categories %>
</div>